import 'dart:typed_data'; // Required for Uint8List
import '../../../../services/database_service.dart';
import '../../../../services/api_service.dart';
import 'model.dart';

class ContainerRepository {
  final DatabaseService _db = DatabaseService();
  final ApiService _api = ApiService();

  static const String _collection = 'user_containers';

  // ===========================================================================
  // 1. SMART ANALYSIS (The Bridge to AI)
  // ===========================================================================

  /// Takes image bytes and filename, sends to AI, and returns a "Draft" Container.
  ///
  /// [imageBytes] - The raw data of the image (Uint8List).
  /// [fileName] - The name of the file (e.g., 'photo.jpg') for the backend.
  ///
  /// Returns NULL if analysis failed.
  Future<UserContainer?> analyzeContainerImage(
    Uint8List imageBytes,
    String fileName,
  ) async {
    try {
      // 1. Delegate to API (Now accepts bytes instead of File)
      final rawData = await _api.recognizeContainer(imageBytes, fileName);

      if (rawData == null) return null;

      // 2. Convert Raw JSON to a Model (Draft)
      // We create a fresh instance but don't save it to DB yet.
      return UserContainer.create(
        name: rawData['name'] ?? 'New Container',
        volume: (rawData['volume'] as num?)?.toInt() ?? 0,
        iconType: rawData['icon_type'] ?? 'cup', // Ensure key matches backend
      );
    } catch (e) {
      print("❌ [Repo] Analysis failed: $e");
      return null;
    }
  }

  // ===========================================================================
  // 2. DATABASE OPERATIONS (CRUD)
  // ===========================================================================

  // --- READ ---
  Future<List<UserContainer>> getAllContainers() async {
    final rawData = await _db.getAllFromCollection(_collection);
    return rawData.map((map) => UserContainer.fromMap(map)).toList();
  }

  // --- CREATE ---
  Future<void> saveContainer(UserContainer container) async {
    // Uses the ID generated by the UserContainer.create() factory
    await _db.saveDocument(_collection, container.id, container.toMap());
  }

  // --- UPDATE ---
  Future<void> updateContainer(UserContainer container) async {
    await _db.updateInCollection(_collection, container.id, container.toMap());
  }

  // --- DELETE ---
  Future<void> deleteContainer(String id) async {
    await _db.deleteFromCollection(_collection, id);
  }
}
